bai_1_in_5_dong_dau()
bai_2_so_dong_so_cot()
bai_3_in_ten_cot()
bai_4_type_of_the_column_name()
bai_5_lay_cot_country()
bai_6_lay_5_country_cuoi()
bai_7_lay_country_continent_year()

bai_8_get_first_and_100th_row()
bai_9_get_first_and_last_column()
bai_10_get_last_row()
bai_11_select_specific_rows()
bai_12_get_43rd_country()
bai_13_get_specific_rows_columns()